CREATE DATABASE EcomDW;

USE EcomDW;
GO

CREATE SCHEMA stg AUTHORIZATION dbo;


CREATE SCHEMA dw AUTHORIZATION dbo;

CREATE SCHEMA etl AUTHORIZATION dbo;

CREATE SCHEMA rpt AUTHORIZATION dbo;